print("SnakyDev - Band Name Generator!")
city = input("What's the name of city you grew up in?\n ")
pet = input("What is your favourite pet?\n ")
print("Your band name could be " + city + " " + pet + "🎸")
print("\nThank you for using SnakyDev-Band Name Generator!\n")
